package tercero.com.base.models;

public enum RolArtistaEnum {
    SOLISTA, VOCALISTA, GUITARRISTA, BAJISTA, BATERISTA, TECLADISTA, SAXOFONISTA, TRUMPETISTA, PERCUSIONISTA, VIOLINISTA, VIOLONCELISTA, MANDOLINISTA, FLAUTISTA, HARMONICISTA, CANTANTE, COMPOSITOR, PRODUCTOR;
}
